# configs/model/eeg_model_config.yaml

feature_extractor:
  embedding_dim: 256
  name: "eeg_resnet18"
  in_channels: 62
  mlp_hidden_dims: [256, 128]

model_head:
  type: "classification"
  num_classes: 3