# configs/dataset/seed.yaml
# Defines everything related to the SEED dataset.

name: SEED
data_dir: "/data3/huangjiehang/seed"
sfreq: 200
num_channels: 62

preprocess:
  downsample:
    enable: true
    target_sfreq: 128.0
  segment:
    enable: true
    window_sec: 20
    step_sec: 4.0
  feature_extraction:
    enable: true
    type: 'de_emt'
    bands:
      delta: [1, 4]
      theta: [4, 8]
      alpha: [8, 14]
      beta: [14, 31]
      gamma: [31, 45]
    sub_segment:
      enable: true
      window_sec: 2
      step_sec: 0.5
  normalize: true