# configs/training/default.yaml
# Default training parameters.

device: "cuda"
seed: 42
batch_size: 64
epochs: 50
optimizer:
  type: Adam
  lr: 0.005
  weight_decay: 0.0001
early_stopping:
  monitor_metric: "accuracy"
  patience: 20
  mode: "max"
log_interval: 10
num_workers: 4