# configs/task/classification_config.yaml

type: "classification"
num_classes: 2
loss_function: "CrossEntropyLoss"
metrics:
  - "accuracy"
  - "f1_weighted"
  - "precision_weighted"
  - "recall_weighted"
