# configs/task/classification_binary.yaml
# Defines a binary classification task.

type: "classification"
num_classes: 2
loss_function: "CrossEntropyLoss"
metrics:
  - "accuracy"
  - "f1_weighted"
  - "precision_weighted"
  - "recall_weighted"

model_head:
  type: "classification"
  num_classes: 2